### ISSUE TITLE
Marketplace link doesn't work

### ISSUE THREAD

**Issue by khdc** [madskristensen/EmphasizeWords#1]
**Describe the bug**
The marketplace link doesn't work and the extension cannot be found.

**To Reproduce**
1. Click the link
2. Try searching on the marketplace

**Comment by madskristensen** [comment]
I took it down from the Marketplace because we're revising the product strategy.

**Comment by khdc** [comment]
Bummer. That would have been helpful for me. Thanks for all your hard work.

**Comment by madskristensen** [comment]
Grab it here from the bottom of the page: https://github.com/madskristensen/BionicReading/actions/runs/4349039739

**Comment by madskristensen** [comment]
...and let me know if you find this to be useful for reading code

**Comment by khdc** [comment]
Just installed it. Wow... Like a breath of fresh air for my brain. I look at tons of code everyday. Thank you!
